# Site settings
title: Game Dev Jaemin Jung
email: windyvill@naver.com
url: https://Gleam21.github.io
description: "유니티 기반의 게임 개발자"
keywords: "unity, developer,C#,game"
skills: "C# Developer,Unity Developer, Server Developer"
meta_author: 재민 정

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Jaemin Jung
  location: Skills
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: bitbucket
    url: 
  - title: github
    url: http://github.com/Gleam21

# Postal address (add as many lines as necessary)
address:
  - line: C#, Unity
  - line: 

# Credits content
credits: "유니티로 게임을 개발하는 개발자"

# Build settings
markdown: kramdown
permalink: pretty
